### ISSUE TITLE
Can't get Bragibooks to start anymore

### ISSUE THREAD

**Issue by rubylaser** [djdembeck/bragibooks#90]
Hello, I've been running Bragibooks in a Docker Container for months now.  I went to use it today for some audio books, and the container isn't working.  I've tried updating the image. I removed the container and image and did a new docker-compose up, but I still see this same error.  Any help you could offer would be appreciated because I love Bragibooks.

Here is my docker-compose.yml

```
version: '3.3'
services
    bragibooks:
        container_name: bragibooks
        environment:
          - UID=1000
          - GID=1000
          - LOG_LEVEL=WARNING
        volumes:
          - /docker/containers/bragibooks/config:/config
          - /docker/downloads/completed/Audiobooks:/input
          - /storage/audiobooks:/output
        ports:
          - 8001:8000
        restart: unless-stopped
        image: ghcr.io/djdembeck/bragibooks:main
```

Here is what I'm seeing in the container's logs.
```
Starting with UID: 1000, GID: 1000
useradd: user 'user' already exists
Traceback (most recent call last):
  File "/home/app/web/manage.py", line 45, in <module>
    main()
  File "/home/app/web/manage.py", line 41, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 386, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 87, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 74, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 183, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/app/web/bragibooks_proj/settings.py", line 62, in <module>
    CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS").split(',')
AttributeError: 'NoneType' object has no attribute 'split
```
Even docker exec immediately dumps me right back to the host.
```
root@frontend:/docker# docker exec -it bragibooks /bin/bash
root@0994a652e319:/home/app/web# 
root@frontend:/docker# docker exec -it bragibooks /bin/bash
Error response from daemon: Container 0994a652e319b21da7ec1dcf55f72b5ad3fc1564504ece619e27c5d8fed37e48 is restarting, wait until the container is running
```

**Comment by djdembeck** [comment]
Seems a bad merge https://github.com/djdembeck/bragibooks/pull/82

Will fix

**Comment by rubylaser** [comment]
I figured it out. Once I added in the the CSRF option to my docker-compose.yml it worked. I don't use a reverse proxy for bragibooks, so this behavior/requirement seems like a bug. I just put in a fake hostname, restarted and it started.

**Comment by djdembeck** [comment]
Please try the new `develop` or `main` images. This should be resolved in https://github.com/djdembeck/bragibooks/pull/91/

Basically that merge should have been into dev not main

**Comment by rubylaser** [comment]
The latest main branch pull is working great. Thanks again for the lightning fast response!
